### ISSUE TITLE
Deviot not detecting PlatformIO

### ISSUE THREAD

**Issue by Kenny11CZ** [gepd/Deviot#109]
Hi there, I've had problem with installing Deviot because of this error:
`ERROR: The executable "D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe" could not be run: [Error 5] Access is denied`
which appeared in PlatformIO installation, so I tried install PlatformIO by myself, but Deviot do not detect that installation and it it fails again during installation.

Both errors were mentioned here, but no solution worked for me.

I would say the problem is this line in console log:
`'"D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\pio"' is not recognized as an internal or external command,operable program or batch file.`

Additional informations:
No Atom installed, PlatformIO core only.
OS: Windows 10
ST Build: 3124
Non-portable version

**platformio --version**
`PlatformIO, version 3.2.1`

**pio --version**
`PlatformIO, version 3.2.1`

**python --version**
`Python 2.7.12`

**virtualenv --version**
`15.0.3`

**full console log**
`DPI scale: 1.25
startup, version: 3126 windows x32 channel: stable
executable: /D/Programs/Sublime Text 3/sublime_text.exe
working dir: /D/Programs/Sublime Text 3
packages path: /D/Programs/Sublime Text 3/Data/Packages
state path: /D/Programs/Sublime Text 3/Data/Local
zip path: /D/Programs/Sublime Text 3/Packages
zip path: /D/Programs/Sublime Text 3/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.617538
startup time: 0.681538
first paint time: 0.699538
first paint time: 0.699538
no such context .regex..dart in Packages/Dart/Dart.tmLanguage
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in D:\Programs\Sublime Text 3\Data\Installed Packages\BracketHighlighter.sublime-package", line 24, in <module>
ImportError: No module named 'mdpopups'
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
error: unable to open crawldb (D:\Programs\Sublime Text 3\Data\Index), indexing is unavailable
indexing: crawldb not available, indexing abandoned
reloading plugin BracketHighlighter.bh_support
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Phpcs.phpcs
reloading plugin PHPIntel.intel
reloading plugin PHPIntel.phpintel
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "phpintel in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 459, in <module>
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 61, in get_all_token_names
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 453, in PHPopen
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
reloading plugin PHPIntel.phpparser
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 459, in <module>
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 61, in get_all_token_names
  File "phpparser in D:\Programs\Sublime Text 3\Data\Installed Packages\PHPIntel.sublime-package", line 453, in PHPopen
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
reloading plugin SublimeLinter-contrib-dartanalyzer.linter
SublimeLinter: dartanalyzer linter loaded 
reloading plugin SublimeLinter-contrib-tslint.linter
SublimeLinter: tslint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin Themr.themr
reloading plugin ColorPicker.sublimecp
reloading plugin Dart.__init__
reloading plugin Dart._init_
reloading plugin Dart._init_check
reloading plugin Dart.AAA
reloading plugin Dart.analyzer
reloading plugin Dart.autocomplete
reloading plugin Dart.browser
reloading plugin Dart.cmds_search
reloading plugin Dart.comment
reloading plugin Dart.config_check
reloading plugin Dart.dartlint
Dartlint plugin loaded.
reloading plugin Dart.dev_cmds
reloading plugin Dart.docgen
reloading plugin Dart.edit
reloading plugin Dart.execute
reloading plugin Dart.format
reloading plugin Dart.misc
reloading plugin Dart.navigation
reloading plugin Dart.polymer
reloading plugin Dart.pub_support
reloading plugin Dart.run
reloading plugin Dart.stagehand
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin TypeScript.main
2017-02-27 19:42:29,277: 7580: INFO: Logging configured to log to file: D:\Programs\Sublime Text 3\Data\Packages\TypeScript\typescript\TS.log
2017-02-27 19:42:29,335: 7580: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: D:\Programs\Sublime Text 3\Data\Packages\TypeScript\tsserver\tsserver.js
Path of tsc.js: D:\Programs\Sublime Text 3\Data\Packages\TypeScript\tsserver\tsc.js
Trying to spawn node executable from: node
ref view not found
Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\_init_check.py", line 82, in plugin_loaded
    check()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\_init_check.py", line 74, in check
    SDK().check_for_critical_configuration_errors()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 199, in check_for_critical_configuration_errors
    return self.path
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 71, in __get__
    value = self.validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 70, in validate
    value = super().validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 81, in validate
    assert isinstance(value, self.expected_type), 'validation failed for "%s". Got %s, expected %s' % (self.name, type(value), self.expected_type)
AssertionError: validation failed for "dart_sdk_path". Got <class 'NoneType'>, expected <class 'str'>
Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\analyzer.py", line 40, in plugin_loaded
    sdk.check_for_critical_configuration_errors()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 199, in check_for_critical_configuration_errors
    return self.path
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 71, in __get__
    value = self.validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 70, in validate
    value = super().validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 81, in validate
    assert isinstance(value, self.expected_type), 'validation failed for "%s". Got %s, expected %s' % (self.name, type(value), self.expected_type)
AssertionError: validation failed for "dart_sdk_path". Got <class 'NoneType'>, expected <class 'str'>
SublimeLinter: debug mode: off 
Traceback (most recent call last):
  File "D:\Programs\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\AAA.py", line 82, in plugin_loaded
    check()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\AAA.py", line 74, in check
    SDK().check_for_critical_configuration_errors()
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 199, in check_for_critical_configuration_errors
    return self.path
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 71, in __get__
    value = self.validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\lib\sdk.py", line 70, in validate
    value = super().validate(value)
  File "D:\Programs\Sublime Text 3\Data\Packages\Dart\sublime_plugin_lib\settings.py", line 81, in validate
    assert isinstance(value, self.expected_type), 'validation failed for "%s". Got %s, expected %s' % (self.name, type(value), self.expected_type)
AssertionError: validation failed for "dart_sdk_path". Got <class 'NoneType'>, expected <class 'str'>
Emmet: No need to update PyV8
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.package_cleanup in D:\Programs\Sublime Text 3\Data\Installed Packages\Package Control.sublime-package", line 77, in run
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Programs\\Sublime Text 3\\Data\\Installed Packages\\EditorConfig.sublime-package'

WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Package Control: Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/Robot-Will/Stino/commits?per_page=1&sha=new-stino.
Package Control: Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/Robot-Will/Stino/commits?per_page=1&sha=new-stino.
ignored packages updated to: ["Deviot", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Deviot.DeviotStarter
Could not import subprocess32 module, falling back to subprocess module
generating syntax summary
no such context .regex..dart in Packages/Dart/Dart.tmLanguage
generating meta info summary
'"D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\pio"' is not recognized as an internal or external command,
operable program or batch file.

reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
indexing: crawldb not available, indexing abandoned
New python executable in D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe
ERROR: The executable "D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe" could not be run: [Error 5] Access is denied

WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
ignored packages updated to: ["Deviot", "Vintage"]
unloading plugin Deviot.DeviotStarter
generating syntax summary
no such context .regex..dart in Packages/Dart/Dart.tmLanguage
generating meta info summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The package Deviot has been removed
reloading settings Packages/User/Package Control.sublime-settings
indexing: crawldb not available, indexing abandoned
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
ignored packages updated to: ["Deviot", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Deviot.DeviotStarter
generating syntax summary
no such context .regex..dart in Packages/Dart/Dart.tmLanguage
generating meta info summary
'"D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\pio"' is not recognized as an internal or external command,
operable program or batch file.

reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
indexing: crawldb not available, indexing abandoned
New python executable in D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe
ERROR: The executable "D:\Programs\Sublime Text 3\Data\Packages\User\Deviot\penv\Scripts\python.exe" could not be run: [Error 5] Access is denied
`

**Comment by gepd** [comment]
Hi @Kenny11CZ , I've improved this feature in the in the last version of the plugin, it's not released yet but you can help me to test it, more information here: https://github.com/gepd/Deviot/issues/117

**Comment by Kenny11CZ** [comment]
Nice, Deviot is now successfuly installed, but I don't have any project at this moment to test it on...

**Comment by gepd** [comment]
That is good to know, you can report an issue any time!
