### ISSUE TITLE
DEV no error catch compile failure ascii > 128

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#151]
Before report an issue, please make sure it hasn't been reported before.

### Operating system
osx
### Board used
nodemcu v1
### Description of problem
if you have a higher ascii character in file or accidental char etc

### Steps to Reproduce
stick a ƒ or something in the file
compile, output window says nothing

### Actual Results

Exception in thread Thread-21:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot/platformio/compile.py", line 49, in start_compilation
    self.make_cpp_temp()
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot/platformio/initialize.py", line 113, in make_cpp_temp
    self.add_arduino_lib(cpp_file)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot/libraries/preferences_bridge.py", line 306, in add_arduino_lib
    sketch = file.read()
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 568: ordinal not in range(128)

### Additional info

*You can edit the text above according to your need*

**Comment by gepd** [comment]
This was caused by the experimental function to fix the linter problem, but as I've move the code to a new branch it's not present in the develop, but I'll check this .
