### ISSUE TITLE
Deviot stuck ([ Deviot 2.1.5 ] Starting...)

### ISSUE THREAD

**Issue by Novian3002** [gepd/Deviot#180]
Before report an issue, please make sure it hasn't been reported before.

### Operating system
Ubuntu 17.04 64-bit
### Board used
PRO16MHZATMEGA168
### Description of problem
After pressing upload (alt+e) deviot is stuck `[ Deviot 2.1.5 ] Starting...
`
### Error(s) in ST Console? (View > Show Console)
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 18, in popen
    return subprocess.check_output(argv, stderr=subprocess.STDOUT).strip()
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '['lsusb', '-v', '-s', '5:2']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 70, in usb_lsusb_string
    desc = popen(['lsusb', '-v', '-s', '%s:%s' % (bus, dev)])
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 20, in popen
    raise IOError('lsusb failed')
OSError: lsusb failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 45, in start_upload
    self.check_port_selected()
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/project_check.py", line 230, in check_port_selected
    ports_list = self.get_ports_list()
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 127, in get_ports_list
    ports_list = serial_port_list()
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 29, in serial_port_list
    ports = list(list_ports.comports())
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 123, in comports
    return [(d, describe(d), hwinfo(d)) for d in devices]
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 123, in <listcomp>
    return [(d, describe(d), hwinfo(d)) for d in devices]
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 94, in describe
    return usb_lsusb_string(sys_usb)
  File "/home/sven/.config/sublime-text-3/Packages/Deviot (Arduino IDE)/libraries/pyserial/tools/list_ports_posix.py", line 81, in usb_lsusb_string
    return base
```
NameError: global name 'base' is not defined

### Steps to Reproduce
1. Write some code, compile it.
2. Try to upload it
### Actual Results
Deviot gets stuck
### Expected Results
Deviot uploads the code to my board
### Additional info
This is probably an issue on my side

**Comment by Novian3002** [comment]
Fixed itself after restarting
