### ISSUE TITLE
dev menu issues

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#181]
```
Exception in thread Thread-40:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\user\Documents\projects\bin\sublimetext\Data\Packages\Deviot (Arduino IDE)\platformio\upload.py", line 45, in start_upload
    self.check_port_selected()
  File "C:\Users\user\Documents\projects\bin\sublimetext\Data\Packages\Deviot (Arduino IDE)\libraries\project_check.py", line 230, in check_port_selected
    QuickMenu().quick_serial_ports()
AttributeError: 'QuickMenu' object has no attribute 'quick_serial_ports'

Exception in thread Thread-43:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\user\Documents\projects\bin\sublimetext\Data\Packages\Deviot (Arduino IDE)\platformio\upload.py", line 45, in start_upload
    self.check_port_selected()
  File "C:\Users\user\Documents\projects\bin\sublimetext\Data\Packages\Deviot (Arduino IDE)\libraries\project_check.py", line 230, in check_port_selected
    QuickMenu().quick_serial_ports()
AttributeError: 'QuickMenu' object has no attribute 'quick_serial_ports'
```

![sublime_text_2017-09-28_10-09-38](https://user-images.githubusercontent.com/807787/30974466-5946278a-a435-11e7-85b3-a4d71f2ccc8f.png)

**Comment by gepd** [comment]
Errors fixed.

To see the right strings in the menu go to the language selection and select English again.
