### ISSUE TITLE
dev serial baud rate problem

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#190]
osx

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/commands/deviot_choose_baudrate.py", line 14, in run
    items = Quick.serial_baudrate_list()
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/quick_menu.py", line 408, in serial_baudrate_list
    self.index = items.index(current)
ValueError: 115200 is not in list
```

**Comment by gepd** [comment]
Can you tell me the steps to reproduce this issue?

**Comment by tablatronix** [comment]
I am just trying to click serial baud rate

**Comment by Booli** [comment]
Same problem here: 

```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/pim/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/commands/deviot_choose_baudrate.py", line 14, in run
    items = Quick.serial_baudrate_list()
  File "/Users/pim/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/quick_menu.py", line 408, in serial_baudrate_list
    self.index = items.index(current)
ValueError: 19200 is not in list
```
I noticed that there is no arrow also any more, so I can't select different Baudrates.

**Comment by gepd** [comment]
I've tried to replicate this issue but I couldn't. For me it's working in OSX, Linux and Windows

Try this:
`Deviot Menu > Select Language` and select the same language you already are using, it will make update the menu file.

@Booli There not arrow now because baudrate options now are displying in a quick panel

**Comment by gepd** [comment]
I think I've found the problem, I've fixed and updated to `dev.10`

**Comment by gepd** [comment]
reopen this issue if you keep getting this error
