### ISSUE TITLE
NEW DEV BUGS

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#209]
The new commits issues.

Ill just post them here before creating a bunch on new dev issues.

## terminal select all
Windows
The deviot terminal get selected all when it is running. It is very odd. as it updates all the text highlights and stays selected.

**Comment by tablatronix** [comment]
### Serial pane
Serial monitor forces new layout pane, kind of annoying, I already use serial in pane, but I don't always want it, it also adds new panes when I already have one open, sometimes I have multiple terminals open also. Interesting feature, might need some polishing or options. 

If i already have custom layout, I don't need new panes created, so it conflicts with my layouts and messes stuff up

**Comment by tablatronix** [comment]
Windows
Compile linter context errors not working anymore ( I know they were wrong line numbers and annoying but they were very useful, I stated getting used to them )
(FYI aside, arduino precompiler says it adds #linenum directives to source code, wonder if that would help)

**Comment by gepd** [comment]
> Every time I close and restart serial, it creates an additional new pane, also.

What is you O.S?
I'm on windows and that is not the behavior I get when I restart it

> Also if I do shortcut for serial monitor , it does not seem to work always, but seems to only work when > that pane is focused, this was not the case in the past.

I've not change any code related with the shortcut(s), can you check if there is an error in the console when you run the shortcut?

> also please fix #171

it was fixed in `dev14`

**Comment by tablatronix** [comment]
Sorry it has nothing to do with shortcuts, the menu does it also, open serial monitor, new pane is created, close serial tab, open serial monitor , new pane is created again ad infinitum

**Comment by tablatronix** [comment]
I think the shortcut not working was something to do with the focus and text selection constantly changing. I will see if it happens agian.

**Comment by tablatronix** [comment]
ahh with regards to the shortut issue, I did not realize that the shortcut toggled the serial monitor, I was toggling it on and off accidentally, while trying to restart it , It is hard to know when its on or off.

**Comment by gepd** [comment]
> could the tab title be changed to reflect it ?

In `dev14` I've introduced a new feature that makes the status bar change the color to green when the serial monitor is connected, and red for 3 seconds when it's disconnected. 

However there are some issues I'm solving now related to this new feature (the color keeps green when you close the window)

The updates will come in a few hours

**Comment by tablatronix** [comment]
Will this continue to work with multiple serial windows running ?

**Comment by tablatronix** [comment]
![2018-02-12_13-27-08](https://user-images.githubusercontent.com/807787/36115417-a6a84d6c-0ff8-11e8-83ab-5e0d0d34122d.gif)

not sure if gifs work but this is a gif of several issues

**Comment by gepd** [comment]
I'll add a modification to show the color in the tab instead of the status bar, that way shouldn't be a problem

**Comment by tablatronix** [comment]
This is how I use serial alot, sometimes even 4 uarts at a time ( debug uarts etc )
![2018-02-12_13-36-09](https://user-images.githubusercontent.com/807787/36115803-cf99ca38-0ff9-11e8-8d1c-534cae360830.gif)

**Comment by gepd** [comment]
> console doesn't work until its created

I'll solved this now, the rest of the issues are already solved. I'll it push it all together

**Comment by tablatronix** [comment]
Sounds good, let me know if you need anything to be tested, I will follow up also on OSX later

**Comment by gepd** [comment]
#### Released `dev.15`
> The deviot terminal and serial monitor text gets selected all(highlighted) when it is running. It is very odd. as it updates all the text highlights and stays selected.

Fixed

> Serial monitor forces new layout pane, kind of annoying, I already use serial in pane, but I don't always want it, it also adds new panes when I already have one open, sometimes I have multiple terminals open also (I change com port and start, so i can debug multiple uarts and devices at once). Interesting feature, might need some polishing or options.
>
> If i already have custom layout, I don't need new panes created, so it conflicts with my layouts and messes stuff up.

I've added the menu to edit the deviot preferences, go to `Preferences > Package Settings > Deviot > Settings`

Changes the option `terminal_direction` and `monitor_direction` to `self`. It will avoid to create a new panel

> Compile linter context errors not working anymore ( I know they were wrong line numbers and annoying but they were very useful, I stated getting used to them )
> (FYI aside, arduino precompiler says it adds #linenum directives to source code, wonder if that would help)

I hope to bring back this soon

> console doesn't work until its created

Fixed too

**Comment by tablatronix** [comment]
osx first run update, it said could not import color_ something, some color file and deviot didnt start, I restarted and it works. Ill see if i logged it somewhere.

**Comment by tablatronix** [comment]
osx serial not working

```
reloading settings Packages/User/deviot.sublime-settings
Exception in thread Thread-519:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 94, in start
    if is_available(self.port):
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 182, in is_available
    serial.open()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/pyserial/serialposix.py", line 271, in open
    self._reconfigure_port(force_update=True)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/pyserial/serialposix.py", line 373, in _reconfigure_port
    if self._stopbits == serial.STOPBITS_ONE:
NameError: global name 'serial' is not defined
```

**Comment by tablatronix** [comment]
upload error

```

top level value must be an array
Exception in thread Thread-563:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 40, in start_upload
    self.check_port_selected()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/project_check.py", line 229, in check_port_selected
    config.read(ini_path)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/readconfig/__init__.py", line 99, in read
    if(not path.exists(filepath)):
  File "./python3.3/genericpath.py", line 18, in exists
TypeError: can't specify None for path argument
```

**Comment by gepd** [comment]
I've pushed a commit to solve the serial problems, checks and let me know if you keep getting that errors.

Upload compiles too, I suspect it's related with the serial issue

**Comment by tablatronix** [comment]
here is that upgrade error, osx and windows.

```
reloading plugin Deviot (Arduino IDE).Deviot
Traceback (most recent call last):
  File "C:\Users\alverson\Documents\projects\bin\sublimetext\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\alverson\Documents\projects\bin\sublimetext\Data\Packages\Deviot (Arduino IDE)\Deviot.py", line 20, in <module>
    from .libraries.paths import getDeviotUserPath, getPluginName, status_color_folder
ImportError: cannot import name status_color_folder
```

deviot does not start, after restarting ST it works.

**Comment by tablatronix** [comment]
terminal_direction not self still makes additional panes, not sure if you meant that was fixed or not.
`self` works as before 👍

**Comment by tablatronix** [comment]
deviot console does not scroll if serial auto scroll off.

**Comment by gepd** [comment]
No new panel is created when I change the setting in my machine:

![panel_direction](https://user-images.githubusercontent.com/7091609/36159300-1f0706d0-10bd-11e8-8130-e5e56941ce66.gif)

**Comment by tablatronix** [comment]
When NOT self

**Comment by tablatronix** [comment]
windows
starting serial monitor opens deviot console.

**Comment by gepd** [comment]
> When NOT self

That is the intention when is not self, I don't understand what do you expect

**Comment by gepd** [comment]
> windows
> starting serial monitor opens deviot console.

In the gif I opened the serial monitor two times and it's not happening. I tried the shortcut and from menu, I can't replicate that

**Comment by tablatronix** [comment]
hmm, if i set it to `right`, it still opens multiple panes over and over, that is what I meant.

**Comment by tablatronix** [comment]
windows
clean monitor view does not appear to work, I assume it is meant to empty the buffer completely, or is this constrained to 20k lines like auto ?

**Comment by gepd** [comment]
> hmm, if i set it to right, it still opens multiple panes over and over, that is what I meant.

yep, to avoid that you have to change the value to `self`

**Comment by gepd** [comment]
> clean monitor view does not appear to work, I assume it is meant to empty the buffer completely, or is this constrained to 20k lines like auto ?
it should work regardless of the 20 lines, I'll check that

**Comment by tablatronix** [comment]
did you see this one too, i slipped it in there above

windows
starting serial monitor opens deviot console.

**Comment by gepd** [comment]
I tried to replicate it, but I can't. Look the gif I [posted](https://github.com/gepd/Deviot/issues/209#issuecomment-365310351), it doesn't open the deviot console

**Comment by tablatronix** [comment]
![2018-02-13_11-09-59](https://user-images.githubusercontent.com/807787/36163272-80a77794-10ae-11e8-8106-0f9248a5fb79.gif)

**Comment by gepd** [comment]
Is that windows?
which version?

**Comment by tablatronix** [comment]
windows, should be latest of both

**Comment by gepd** [comment]
> Also where can I find my .elf file ?

If you are using the PIO structure it will be located in the `.pioenvs` folder (same folder of your sketch) If you're not using it, it should be in `%temp%\Deviot\your_sketch_name\.pioenvs`

**Comment by tablatronix** [comment]
Thanks I was trying to automate this, and maybe add it somehow and grab the environments from pio.

```
java -jar "%userprofile%\Documents\projects\electronics\EspStackTraceDecoder.jar" "%userprofile%\.platformio\packages\toolchain-xtensa\bin\xtensa-lx106-elf-addr2line" "%userprofile%\AppData\Local\Temp\Deviot\OnDemandConfigPortal\.pioenvs\nodemcuv2_dev\firmware.elf" "%userprofile%\Documents\projects\electronics\exception.txt"
```

**Comment by gepd** [comment]
> I noticed in my deviot console the filenames are being clipped for the build assets.
eg. nodemcuv2_dev

Fixed with: https://github.com/gepd/Deviot/commit/db9396d09142179f37e2e2c1aa093c3c5485a0e3

**Comment by gepd** [comment]
You can use:
`%temp%\Deviot\OnDemandConfigPortal\.pioenvs\nodemcuv2_dev\firmware.elf`

Are you using python?

**Comment by tablatronix** [comment]
Gonna try so i can use it cross platform and add to ST

**Comment by gepd** [comment]
It need to be an standalone plugin?

**Comment by tablatronix** [comment]
Nope, ST has tools, build tools, and instant plugins, and macros etc.

**Comment by tablatronix** [comment]
osx, probably windows also
I noticed now on compile error, with `"monitor_direction": "self",`, the monitor restarts in self pane (current focused pane), which is a bit annoying, so it stops the monitor running, opens a new one in the current pane for example, whereas it used to just resume as it was.

**Comment by gepd** [comment]
That is because you are using the `upload` option instead of `compile`. 

`Upload` needs the serial port so it's closed

![monitor_reset](https://user-images.githubusercontent.com/7091609/36186931-e7a94716-1120-11e8-9a16-b152bd36d6c9.gif)

**Comment by tablatronix** [comment]
Of course
Ill make a gif, my serial restarts in the focused pane, the left pane. On osx

**Comment by tablatronix** [comment]
Windows
console still opens when starting serial monitor.

**Comment by tablatronix** [comment]
so far very stable, been using it all day. Will try to test advanced stuff like ota etc.

**Comment by gepd** [comment]
I've pushed a possible fix for the console issue (https://github.com/gepd/Deviot/commit/9b77d5cbab1bcab06ff88f12627639252d010a61)

I'll add two more features before release the next version
1. Linter context errors
2. An option to cancel the compile/upload process

**Comment by tablatronix** [comment]
using osx today, also looking pretty good and stable.

Can you add a timestamp to the end of the deviot console when done with stuff, I know its at the top, but having an end stamp would be useful

**Comment by tablatronix** [comment]
Does serial monitor log to a temp file, or it is just a buffer?

**Comment by gepd** [comment]
> Can you add a timestamp to the end of the deviot console when done with stuff
Yes I can, I did that in the past for the same reason. When I rewrite the code I forgot to added again.

> Does serial monitor log to a temp file, or it is just a buffer?
It's just a buffer, but wouldn't it be a problem to be stored in a file. Do you want this for the trace decoder?

**Comment by tablatronix** [comment]
Yes I figured I can run external stuff on it in real time if so, without hooking into ST to do it.

I have been using log highlighter for coloring the terminal,  serial ports and live log files, its pretty powerful.

**Comment by gepd** [comment]
Excelent. Maybe I can log only the backtraces and exceptions, that way would be easy

**Comment by tablatronix** [comment]
That might be too specific for other uses, unless you were adding specfic debug save to file feature maybe with regex i guess.

**Comment by gepd** [comment]
>That might be too specific for other uses, unless you were adding specfic debug save to file feature maybe with regex i guess.

Yes, it's a good idea, I don't know how many people will need that feature, but maybe will be good to have it

I've added the

**Comment by tablatronix** [comment]
only thing i noticed is that serial terminal takes a long time now to start back up, even adding a 5000 delay, i miss the boot sometimes.

**Comment by gepd** [comment]
You mean, when you are using the serial monitor, uploads your firmware and the monitor starts again?

**Comment by tablatronix** [comment]
Yup

**Comment by tablatronix** [comment]
I think auto clean broke, on osx i have 77k lines

**Comment by gepd** [comment]
good catch, fixed

**Comment by tablatronix** [comment]
protip, at 77k lines it just stops apparently, lol i cleared it and it started printing away.

**Comment by tablatronix** [comment]
time to be picky
lol

```
========================= [SUCCESS] Took 10.40 seconds =========================

================================== [SUMMARY] ==================================
Environment esp32doit-devkit-v1	[SKIP]
Environment nodemcuv2_dev      	[SUCCESS]
========================= [SUCCESS] Took 10.40 seconds =========================

[Fri Feb 16 22:54:43 2018]
```

success is displayed twice with same timestamp, remove one, and the 2 empty  lines and you get 3 more lines of info in a smaller panel... just saying... lol

still seems pretty stable, and running well all around.

Loving this version so far.

![screen shot 2018-02-16 at 10 57 01 pm](https://user-images.githubusercontent.com/807787/36338155-3900f8c2-136d-11e8-98a6-c5ac0a40d233.png)

**Comment by gepd** [comment]
> serial takes too long to start

I'll have to check this when I have a osx device on my hands, there is not a deliberate delay in that part of the code, but I'll check it later to reduce it somehow

> protip, at 77k lines it just stops apparently, lol i cleared it and it started printing away again

Did you try that after the fix? the bug was causing an error, so is possible it was causing the stop

> success is displayed twice with same timestamp, remove one, and the 2 empty lines and you get 3 more lines of info in a smaller panel... just saying... lol

It's displayed by PIO. Maybe the best solution is to add the regex filter (thinking in the debug tool too) and remove it, I'll let it to the next release

**Comment by tablatronix** [comment]
I will retest, Is it possible to set global environments somewhere?
Does pio check for ini files along some path?

**Comment by gepd** [comment]
> I will retest, Is it possible to set global environments somewhere?

Global environments for compile? or to do what?

> Does pio check for ini files along some path?

In Deviot the ini file will be checked in the same path where the sketch is stored, also in the parent folder or in the system `temp\deviot` folder

Normally PIO Core will search the `platformio.ini` in the current working directory but you can change this with `--project-dir` [More Info](http://docs.platformio.org/en/latest/userguide/cmd_run.html?highlight=--project-dir#cmdoption-platformio-run-d)

**Comment by tablatronix** [comment]
Yeah like if i create a new file, can it just use some global environments and create the ini file for me for example. I probably use pio completely wrong, but that is exactly why I use deviot, its not annoying like the atom IDE where you have to have strict projects , i just want to throw a file together, select board, compile and have a new platformio.ini and be running. It kind of works already like this.

**Comment by gepd** [comment]
Maybe you can use my python library to read and write ini files: https://github.com/gepd/ReadConfig
I started that library to work with PIO, it's really easy to use. If you are working with ST, you shouldn't have any problem, it's used by Deviot too

**Comment by tablatronix** [comment]
I noticed my .cpp file shave a deviot syntax, not c++, and my autocomplete doesn't work well.
If i change it to c++ it works properly and shows my classnames and methods etc.
Is that fixable? I do like the deviot syntax better

**Comment by tablatronix** [comment]
I figured out the problem with the console, its not those extra lines, it  is that it seems to scroll past the buffer leaving lots of empty space and I can never see the output as well.

![sublime_text_2018-02-19_08-09-09](https://user-images.githubusercontent.com/807787/36381855-8328932a-154c-11e8-8e61-7ca19ab246e8.png)

**Comment by gepd** [comment]
> I noticed my .cpp file shave a deviot syntax, not c++, and my autocomplete doesn't work well.
If i change it to c++ it works properly and shows my classnames and methods etc.
Is that fixable? I do like the deviot syntax better

I'll check how to improve this, can you give me an example to reproduce that diference?

> I figured out the problem with the console, its not those extra lines, it is that it seems to scroll past the buffer leaving lots of empty space and I can never see the output as well.

Yes I'm using a new method to scroll lines in the console, what you can do is set the `scroll_past_end` option to `false` in the ST settings

> `Error:` and `[ERROR]` be syntax scoped ?

In don't see where is `Error:` but anything in the console can be syntax scoped 

I also fell like the console syntax need a lot of work, I'll start to make some changes this week

**Comment by tablatronix** [comment]
I noted this in #254
