### ISSUE TITLE
OSX cant install library

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#244]
```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/libraries.py", line 174, in library_install
    lib_id = self.quick_list[selected][2].split(' ')[0]
IndexError: list index out of range
```
after select lib to install

**Comment by gepd** [comment]
Fixed with: https://github.com/gepd/Deviot/commit/cab2f94491d97700bca103f2eeb36f462553da58
