### ISSUE TITLE
dev cannot start serial monitor

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#260]
This is a new one

```
Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/commands/deviot_toggle_serial_monitor.py", line 15, in callback
    serial.toggle_serial_monitor(port_id)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 290, in toggle_serial_monitor
    serial_monitor = get_serial_monitor(port_id)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 279, in get_serial_monitor
    serial_monitor = SerialMonitor(port_id)
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/serial.py", line 61, in __init__
    version = deviot.version()
NameError: global name 'deviot' is not defined
```

**Comment by gepd** [comment]
fixed
