### ISSUE TITLE
DEV BUG clean attribute error dstop

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#266]
selecting clean, I get this error in console

```
Exception in thread Thread-1663:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/.../Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/clean.py", line 48, in start_cleaning
    self.dstop()
AttributeError: 'Clean' object has no attribute 'dstop'
```

**Comment by gepd** [comment]
Fixed with https://github.com/gepd/Deviot/commit/4a8228fc7bea95379f553fdfd7ee4abebce30511
