### ISSUE TITLE
TypeError when compile or upload

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#278]
OSX

I created a new sketch and saved it somewhere, then tried to compile it

```PHP
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 52, in start_upload
    self.add_option('lib_extra_dirs', append=True)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 320, in add_option
    if(not wipe and option and option not in current):
TypeError: argument of type 'bool' is not iterable







Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 52, in start_upload
    self.add_option('lib_extra_dirs', append=True)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 320, in add_option
    if(not wipe and option and option not in current):
TypeError: argument of type 'bool' is not iterable

Backup saved to: /Users/shawn/.sublime/backups/Users/shawn/.platformio/lib/Adafruit MAX31855 library_ID84/examples/serialthermocouple/serialthermocouple-2019-02-17_01-16-44.ino
Backup saved to: /Users/shawn/.sublime/backups/Users/shawn/.platformio/lib/Adafruit MAX31855 library_ID84/examples/serialthermocouple/serialthermocouple-2019-02-17_01-17-03.ino
Exception in thread Thread-34:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 52, in start_upload
    self.add_option('lib_extra_dirs', append=True)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 320, in add_option
    if(not wipe and option and option not in current):
TypeError: argument of type 'bool' is not iterable

Exception in thread Thread-46:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 52, in start_upload
    self.add_option('lib_extra_dirs', append=True)
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 320, in add_option
    if(not wipe and option and option not in current):
TypeError: argument of type 'bool' is not iterable
```

**Comment by gepd** [comment]
The last commit should fix this
