### ISSUE TITLE
esp32 ota issue

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#295]
After a successful ota, sometimes it doenst finish.

```PHP
Uploading: [============================================================] 100% Done...
99
99
99
99

16:04:10 [INFO]: Waiting for result...
Traceback (most recent call last):
File "/Users/alverson/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/tools/espota.py", line 353, in <module>
sys.exit(main(sys.argv))
File "/Users/alverson/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/tools/espota.py", line 348, in main
return serve(options.esp_ip, options.host_ip, options.esp_port, options.host_port, options.auth, options.image, command)
File "/Users/alverson/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/tools/espota.py", line 220, in serve
except e:
NameError: global name 'e' is not defined
*** [upload] Error 1
========================== [ERROR] Took 80.51 seconds ==========================

================================== [SUMMARY] ==================================
Environment nodemcuv2          	[SKIP]
Environment esp32doit-devkit-v1	[ERROR]
========================== [ERROR] Took 80.51 seconds ==========================
```

```PHP
Traceback (most recent call last):
  File "/Users/alverson/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 241, in _finish
    run_next()
  File "/Users/alverson/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 365, in run_next
    Command().run_command(_COMMAND_QUEUE.popleft())
  File "/Users/alverson/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 184, in run_command
    if(self.cwd):
AttributeError: 'Command' object has no attribute 'cwd'
reloading settings Packages/User/deviot.sublime-settings
reloading settings Packages/User/deviot.sublime-settings
```

**Comment by tablatronix** [comment]
Not sure if its deviot or espota
