### ISSUE TITLE
Device list crashes on MDNS

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#298]
Exception in thread Thread-52:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/upload.py", line 71, in start_upload
    if(not self.check_auth_ota()):
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/project_check.py", line 346, in check_auth_ota
    ports_list = self.get_ports_list()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 135, in get_ports_list
    services = self.get_mdns_services()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/preferences_bridge.py", line 361, in get_mdns_services
    return MDNS.formated_list()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/libraries/mdns/mdns.py", line 111, in formated_list
    board = value['board'].capitalize()
KeyError: 'board'

I have network devices and when they are up this happens.

**Comment by tablatronix** [comment]
Waiting for this to happen again, I have debugging on for mdns current_services
