### ISSUE TITLE
NO idea

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#300]
heh

```PHP
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
Traceback (most recent call last):
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 241, in _finish
    run_next()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 372, in run_next
    Command().run_command(_COMMAND_QUEUE.popleft())
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 184, in run_command
    if(self.cwd):
AttributeError: 'Command' object has no attribute 'cwd'
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
Traceback (most recent call last):
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 241, in _finish
    run_next()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 372, in run_next
    Command().run_command(_COMMAND_QUEUE.popleft())
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 184, in run_command
    if(self.cwd):
AttributeError: 'Command' object has no attribute 'cwd'
reloading settings Packages/User/deviot.sublime-settings
192.168.1.246
{'port': 8266, 'auth_upload': 'no', 'tcp_check': 'no', 'weight': 0, 'address': '192.168.1.246', 'ssh_upload': 'no', 'board': '"PLATFORMIO_NODEMCUV2"', 'priority': 0}
reloading settings Packages/User/deviot.sublime-settings
reloading settings Packages/User/deviot.sublime-settings
```

**Comment by tablatronix** [comment]
Serial doesnt seem to work with this error..
