### ISSUE TITLE
upload failing

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#308]
just sits there, using ota even though serial specified?

```
Building .pio/build/nodemcuv2/firmware.bin
Retrieving maximum program size .pio/build/nodemcuv2/firmware.elf
Checking size .pio/build/nodemcuv2/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [====      ]  38.2% (used 31292 bytes from 81920 bytes)
Flash: [===       ]  33.4% (used 348612 bytes from 1044464 bytes)
Creating BIN file ".pio/build/nodemcuv2/firmware.bin" using ".pio/build/nodemcuv2/firmware.elf"
Configuring upload protocol...
Looking for upload port...
Use manually specified: /dev/cu.SLAB_USBtoUART
Uploading .pio/build/nodemcuv2/firmware.bin
11:16:59 [DEBUG]: Options: {'timeout': 10, 'esp_ip': '/dev/cu.SLAB_USBtoUART', 'host_port': 16422, 'image': '.pio/build/nodemcuv2/firmware.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': False, 'debug': True, 'progress': True}
11:16:59 [INFO]: Starting on 0.0.0.0:16422
11:16:59 [INFO]: Upload size: 380320
```

```
reloading settings Packages/User/deviot.sublime-settings
Traceback (most recent call last):
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 241, in _finish
    run_next()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 372, in run_next
    Command().run_command(_COMMAND_QUEUE.popleft())
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot (Arduino IDE)/platformio/command.py", line 184, in run_command
    if(self.cwd):
AttributeError: 'Command' object has no attribute 'cwd'
reloading settings Packages/User/deviot.sublime-settings
reloading settings Packages/User/deviot.sublime-settings
```

**Comment by tablatronix** [comment]
Dup, I had to select port NONE to reset it, I think I posted this before
