### ISSUE TITLE
the board list won't open

### ISSUE THREAD

**Issue by imalstinco** [gepd/Deviot#326]
Before report an issue, please make sure it hasn't been reported before.

If you need information about an option or feature make sure to first look into the [Deviot Wiki](https://github.com/gepd/Deviot/wiki)

### Operating system
Windows 10
### Board used
ESP32
### Description of problem
I have downloaded the deviot package and the python 2.7, i use the 2.7.18 by the way but then when i wanted to upload the code there is no list of board to pick. so i cant seem to move on
### Error(s) in ST Console? (View > Show Console)
ValueError: No JSON object could be decoded
### Additional info

*You can edit the text above according to your need*
![Screenshot (115)](https://user-images.githubusercontent.com/83685861/117674905-47c2d280-b1d6-11eb-9af3-f44219906311.png)
![Screenshot (116)](https://user-images.githubusercontent.com/83685861/117674910-498c9600-b1d6-11eb-86d9-a1380b992e67.png)

**Comment by tablatronix** [comment]
What does the ST console show?

**Comment by cocoterooo** [comment]
I have de same problem:

The console: 
     ValueError: Extra data: line 1 column 3 - line 3 column 1 (char 2 - 186)
![image](https://user-images.githubusercontent.com/87582495/126047100-d7a002a7-7ba5-4e3b-bef9-9d93e494c2b0.png)

**Comment by Takolo** [comment]
I have the same problem too
The console:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1458, in run_
    return self.run()
  File "C:\Users\Natalia\AppData\Roaming\Sublime Text 3\Packages\Deviot (Arduino IDE)\commands\deviot_select_boards.py", line 7, in run
    items = Quick.boards_list()
  File "C:\Users\Natalia\AppData\Roaming\Sublime Text 3\Packages\Deviot (Arduino IDE)\libraries\quick_menu.py", line 89, in boards_list
    boards = boards_file.read_json()
  File "C:\Users\Natalia\AppData\Roaming\Sublime Text 3\Packages\Deviot (Arduino IDE)\libraries\file.py", line 57, in read_json
    return json.loads(file)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 354, in decode
ValueError: Extra data: line 1 column 3 - line 3 column 1 (char 2 - 188)

**Comment by hijomojo** [comment]
I have a feeling this is another Python version incompatibility thing as PIO requires v 3.6+ but Deviot tries to use 2.7 if it's responsible for installing PIO. Try my guide in the 'issue' mentioned above and see if that helps.
