### ISSUE TITLE
Plugin start penv/bin/python not found inside package folder (and errors afterwards)

### ISSUE THREAD

**Issue by garvamel** [gepd/Deviot#57]
I'm running OSX 10.11.6. Not really sure what information is relevant to help with this so please ask away. Thanks!

Main error (I think) highlighted with **** in code below. I think it is because the folder "Application Support" has a space that is not being escaped:

Currently:
`/bin/sh: /Users/gianpaolo/Library/**Application** Support/Sublime Text 3/Packages/User/Deviot/penv/bin/python`

Maybe it should be:
`/bin/sh: /Users/gianpaolo/Library/**Application\** Support/Sublime Text 3/Packages/User/Deviot/penv/bin/python`
```
startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages
state path: /Users/gianpaolo/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/gianpaolo/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.347639
using gpu buffer for window
startup time: 0.422887
first paint time: 0.45831
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.changes
reloading plugin BracketHighlighter.support
reloading plugin FileDiffs.file_diffs
reloading plugin Go To Definition.Go To Definition
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin WordCount.WordCount
reloading plugin Deviot.DeviotStarter
plugins loaded
**************************************************************
/bin/sh: /Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/User/Deviot/penv/bin/python: No such file or directory
**************************************************************

Package Control: Skipping automatic upgrade, last run at 2016-08-30 11:47:57, next run at 2016-08-30 12:47:57 or after
generating syntax summary
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/DeviotStarter.py", line 133, in run
    self.MENU_LIST = Menu().createBoardsMenu()
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Menu.py", line 50, in createBoardsMenu
    list_env.extend(Tools.getEnvFromFile())
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Tools.py", line 556, in getEnvFromFile
    inipath = getInitPath(view)
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Tools.py", line 530, in getInitPath
    workingpath = getWorkingPath(view)
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Tools.py", line 672, in getWorkingPath
    filepath = Paths.getCWD(view.file_name())
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Paths.py", line 247, in getCWD
    folder_path = os.path.dirname(file_path)
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 413, in savePortCallback
    self.beforeProcess()
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 219, in beforeProcess
    if('src_dir' in INIFILE['platformio']):
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/configobj/configobj.py", line 547, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'platformio'
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 118, in fileCheck
    self.projectRecognition()
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 151, in projectRecognition
    self.beforeProcess()
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/PlatformioCLI.py", line 219, in beforeProcess
    if('src_dir' in INIFILE['platformio']):
  File "/Users/gianpaolo/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/configobj/configobj.py", line 547, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'platformio'
```

**Comment by garvamel** [comment]
Error gone after updating plataformIO as prompted by the plugin. Still can't use the plugin, though. Errors when trying to build. Please close this issue and I will open a new one.
