### ISSUE TITLE
develop osx examples not working

### ISSUE THREAD

**Issue by tablatronix** [gepd/Deviot#95]
When I click examples in menu, nothing happens

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot/DeviotStarter.py", line 296, in run
    self.MENU_LIST = Menu().createLibraryExamplesMenu()
  File "/Users/shawn/Library/Application Support/Sublime Text 3/Packages/Deviot/libs/Menu.py", line 228, in createLibraryExamplesMenu
    library_paths = Paths.getLibraryFolders(platform)
UnboundLocalError: local variable 'platform' referenced before assignment
```

**Comment by tablatronix** [comment]
Threw a 
platform = "" at the beginning of
`createLibraryExamplesMenu`

not sure if its global or not, shrug

**Comment by gepd** [comment]
This is already fixed, please read:  https://github.com/gepd/Deviot/issues/117
